services:
    app:
        build:
            context: .
            args:
                NODE_ENV: production
        env_file: .env
        container_name: volumen-app 
        ports:
            - '${API_PORT}:${API_PORT}'
        depends_on:
            - db
        restart: always
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1G

    db:
        image: postgres:13-alpine
        container_name: volumen-db 
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_NAME}
            POSTGRES_DB: ${DATABASE_NAME}
        volumes:
            - postgres-data-prod:/var/lib/postgresql/data 
        restart: always
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1G

volumes:
    postgres-data-prod: 
        driver: local