services:
    app:
        build: .
        env_file: .env
        container_name: volumen-app-dev
        ports:
            - '${APP_PORT}:${APP_PORT}'
        depends_on:
            - db
        restart: always
        volumes:
            - .:/app
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1G
        command: npm run dev:start 

    db:
        image: postgres:13-alpine
        container_name: volumen-db-dev
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        volumes:
            - postgres-data-dev:/var/lib/postgresql/data
        restart: always
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1G

volumes:
    postgres-data-dev:
        driver: local